# Copyright © 2021 Shell.in.net All rights reserved.
# Licensed under the GNU Lesser General Public License v3.0

- hosts: localhost
  tasks:
    - name: Install mod_perl
      yum: name="mod_perl" state="present"	  
    - name: Restart httpd service
      ansible.builtin.systemd: name="httpd" state="restarted" enabled="yes"
