# Copyright © 2021 Shell.in.net All rights reserved.
# Licensed under the GNU Lesser General Public License v3.0

- hosts: localhost
  tasks:
    - name: Install python3-mod_wsgi
      yum: name="python3-mod_wsgi" state="present"	  
    - name: Restart httpd service
      ansible.builtin.systemd: name="httpd" state="restarted" enabled="yes"
